### ISSUE TITLE
Agent dies when parent shell terminates

### ISSUE THREAD

**Issue by niklasholm** [vuori/weasel-pageant#11]
I'm not sure if this is the same issue as described in known issues, quoted here:

> * If you have an `SSH_AUTH_SOCK` variable set inside `screen`, `tmux` or similar, you exit the WSL console from which the `screen` was *initially started* and attach to the session from another window, the agent connection will not be usable. This is due to WSL/Win32 interop limitations.

Actually I've found that starting an agent inside a tmux session, detaching, and closing the console, and then reusing that agent from another console works perfectly fine, as long as tmux survives. It is actually a valid workaround for my issue:

When launching an agent from one console window (not via tmux), whenever that window closes the agent dies as well. Is this intended? `ssh-agent` does not do this since background processes became supported by WSL. Is it not enough to kill the helper Win32 process to close the console, and keep the main process running?

**Comment by vuori** [comment]
This is a feature. When the conhost process inside which the `weasel-pageant` process was started exits, the connection to the Win32 helper becomes non-functional and (unless something changed in version 1809) it is no longer possible to launch new Win32 processes from the old agent process. In other words, Win32 integration is tied to the conhost from which a WSL process is launched and thus it is not useful to keep the old agent running after that conhost is gone.

**Comment by niklasholm** [comment]
Indeed, the behavior I observe is that when I exit the shell from which the tmux session holding the agent was launched, the console window itself don't want to close. I can see both the agent and the helper process running in task manager. When I close the console (by clicking X), the helper process is killed but the agent survives. When I then start a new console and load the ssh envvars (which I've saved to a file), the helper process is restarted automatically when I call `ssh-add -l`.

You might be wondering; my use case is that I want to share the same agent instance/auth socket between multiple consoles, so the agent dying when the parent console exits breaks this.

I'll try your suggestion and send an PR if successful.

**Comment by niklasholm** [comment]
With this patch the agent remains functional after the console is closed, only terminating the helper process since that is still required for the console windows to not hang around for some reason. The helper process can then be restarted without any issue.

**Comment by vuori** [comment]
PR merged and will be in release 1.3. Thanks.
