### ISSUE TITLE
Connection refused if socket file exists.

### ISSUE THREAD

**Issue by carlolars** [vuori/weasel-pageant#13]
If the file used for the socket exists on disk when starting weasel-pageant for the first time then I get 'connection refused'.
```
$ uname -sor
Linux 4.4.0-17134-Microsoft GNU/Linux

$ ll ~/.weasel-pageant.sock
-rwxrwxrwx 1 carl-oskar carl-oskar 0 Apr 14 12:15 /c/Users/carl-oskar/.weasel-pageant.sock

$ ~/bin/weasel-pageant/weasel-pageant -rbd -a ~/.weasel-pageant.sock
main DEBUG: reuse_socket_path: socket /c/Users/carl-oskar/.weasel-pageant.sock not present
weasel-pageant: connect: Connection refused
```

The faulty state is easy to reproduce, just kill the weasel-pageant process in the Task Manager.

My workaround is to verify that SSH_AUTH_SOCK is set, if not then delete the file and try to start weasel-pageant again:
```
    eval $(~/bin/weasel-pageant/weasel-pageant -rbq -a $SSH_AUTH_SOCK_PATH 2>/dev/null)
    if [[ -z "$SSH_AUTH_SOCK" && -f $SSH_AUTH_SOCK_PATH ]]; then
        rm -f $SSH_AUTH_SOCK_PATH
        eval $(~/bin/weasel-pageant/weasel-pageant -rbq -a $SSH_AUTH_SOCK_PATH 2>/dev/null)
    fi
```

**Comment by vuori** [comment]
Looks like WSL sees your socket as a plain file and the reuse logic gets confused. You're using your Windows profile directory as your WSL home directory?

**Comment by carlolars** [comment]
> 
> 
> Looks like WSL sees your socket as a plain file and the reuse logic gets confused. You're using your Windows profile directory as your WSL home directory?

Yes. The file is as you expected just a plain file in my windows home.
I moved the socket (to /tmp) and now it works as expected. Thanks!
