### ISSUE TITLE
Installation / Configuration in WSL Alpine

### ISSUE THREAD

**Issue by flexguse** [vuori/weasel-pageant#14]
Hi,

I use Windows 1809 Pro and in WSL Alpine 3.9. Unfortunately I'm not able to launch weasel-pageant. It doesn't matter if I download and unzip weasel-pageant directly in Alpine or if I try to use the files installed on Windows using chocolatey.

```bash
NW0W1A1204:~/weasel-pageant-1.3# ll
total 320
drwxr-xr-x    1 root     root           512 Jul 24 16:11 .
drwx------    1 root     root           512 Jul 24 16:11 ..
-rw-r--r--    1 root     root         35147 Jul 24 16:11 COPYING
-rw-r--r--    1 root     root          1397 Jul 24 16:11 COPYING.PuTTY
-rw-r--r--    1 root     root         10552 Jul 24 16:11 README.md
-rw-r--r--    1 root     root        126464 Jul 24 16:11 helper.exe
-rwxr-xr-x    1 root     root         41184 Jul 24 16:11 weasel-pageant

NW0W1A1204:~/weasel-pageant-1.3# ./weasel-pageant
-ash: ./weasel-pageant: not found
```

I suppose I'm missing some required packages but I'm not a C or C++ Linux developer, so I do not have a clue what is missing.

Any ideas?

Cheers,
Christoph

**Comment by vuori** [comment]
What does `ldd weasel-pageant` say? I'm not at all familiar with Alpine Linux, but it sounds like the issue may be that they use musl libc while everyone else uses gnu libc. It may be necessary for you to compile the Linux executable yourself for Alpine.

**Comment by snoopotic** [comment]
I don't recommend using WSL-alpine as it is also not an official alpine. alpine is good for docker base-images, but not as full server system or linux subsystem e.g. for windows.
But I am open you tell me a valid usage for that.
On the other hand the assumption from vuori is right. musl libc is one of that things you will always stumble upon using alpine. :/

**Comment by flexguse** [comment]
Hi Guys,

thanks a lot for your suggestions. Due to a couple of reasons i ended in switchung back to Ubuntu. weasel-pageant works again like a charm.

Cheers,
Christoph

**Comment by vuori** [comment]
Release 1.4 should work on Alpine in case you still need it later.
