### ISSUE TITLE
Process incrementation

### ISSUE THREAD

**Issue by tkapias** [vuori/weasel-pageant#17]
Hello,

I use extraterm with WSL/Debian as root (from sudo -i) and when I close a root shell with exit and come back I find that weasel-pageant processes increment each time until I close the terminal.

I added an alias to close the current weasel-pageant before each exit, I know that we can also set up a trap.

Is there a better solution?

**Comment by vuori** [comment]
That shouldn't happen. What command are you using to start weasel-pageant?

**Comment by tkapias** [comment]
Sorry, I went too fast, I forgot I had modified the launching method because it was stopped at each session and I had to source it manually.

I run weasel-pageant in .bashrc :

```bash
# SSL AGENT for WSL #
#####################

eval $(/mnt/d/Sysadmin/Terminal/weasel-pageant/weasel-pageant -r)
alias exit='/mnt/d/Sysadmin/Terminal/weasel-pageant/weasel-pageant -k && exit'
```

**Comment by tkapias** [comment]
```
# SSL AGENT for WSL #
#####################

eval $(/mnt/d/Sysadmin/Terminal/weasel-pageant/weasel-pageant -r)
#alias exit='/mnt/d/Sysadmin/Terminal/weasel-pageant/weasel-pageant -k && exit'
```

Without the alias for exit I would have a new weasel-pageant for each connection : 

```
admin@DESKTOP-DR3O4DE:~$ sudo -i
ssh-pageant pid 23
root@DESKTOP-DR3O4DE:~# ps faux |grep weasel
root        28  0.0  0.0  14120  1136 tty1     S    16:45   0:00              \_ grep weasel
root        23  0.0  0.0   9164   152 tty1     S    16:45   0:00 /mnt/d/Sysadmin/Terminal/weasel-pageant/weasel-pageant -r
root@DESKTOP-DR3O4DE:~# exit
logout
admin@DESKTOP-DR3O4DE:~$ sudo -i
ssh-pageant pid 45
root@DESKTOP-DR3O4DE:~# ps faux |grep weasel
root        50  0.0  0.0  14120  1136 tty1     S    16:45   0:00              \_ grep weasel
root        23  0.0  0.0   9164   152 tty1     S    16:45   0:00 /mnt/d/Sysadmin/Terminal/weasel-pageant/weasel-pageant -r
root        45  0.0  0.0   9164   148 tty1     S    16:45   0:00 /mnt/d/Sysadmin/Terminal/weasel-pageant/weasel-pageant -r
root@DESKTOP-DR3O4DE:~# exit
logout
admin@DESKTOP-DR3O4DE:~$ sudo -i
ssh-pageant pid 67
root@DESKTOP-DR3O4DE:~# ps faux |grep weasel
root        72  0.0  0.0  14120  1136 tty1     S    16:46   0:00              \_ grep weasel
root        23  0.0  0.0   9164   152 tty1     S    16:45   0:00 /mnt/d/Sysadmin/Terminal/weasel-pageant/weasel-pageant -r
root        45  0.0  0.0   9164   148 tty1     S    16:45   0:00 /mnt/d/Sysadmin/Terminal/weasel-pageant/weasel-pageant -r
root        67  0.0  0.0   9164   148 tty1     S    16:46   0:00 /mnt/d/Sysadmin/Terminal/weasel-pageant/weasel-pageant -r
```

**Comment by vuori** [comment]
Seems like socket re-use is not working for some reason. If you're running release 1809 or later, can you try setting a fixed socket path with the flags `-r -b -a /tmp/pageant.sock` and see if the problem persists?

**Comment by tkapias** [comment]
> 
> 
> Seems like socket re-use is not working for some reason. If you're running release 1809 or later, can you try setting a fixed socket path with the flags `-r -b -a /tmp/pageant.sock` and see if the problem persists?

Perfect, it's working now.

For all intents and purposes, here is more information about my configuration.

- Microsoft Windows 10 Enterprise LTSC (release1809)
- ssh-agent : Keeagent (0.10.1.0) for Keepass
- WSL with Debian

Line in .bashrc : 
```
eval $(/path-to-weasel-pageant/weasel-pageant -r -b -a /tmp/pageant.sock)
```

**Comment by vuori** [comment]
Good to hear, but the issue was pretty strange. Did you have `-a` set before and/or are you using a Windows (drvfs) directory as your WSL `$HOME`?

**Comment by tkapias** [comment]
> 
> 
> Good to hear, but the issue was pretty strange. Did you have `-a` set before and/or are you using a Windows (drvfs) directory as your WSL `$HOME`?

- No there was no setting -a before. I remember that I tried it in a first attempt by creating a Cygwin compatible socket file in Keeagent and I tried to point to it with -a, but it failed.

- My WSL Home is just in a rootfs folder in appdata, no drvfs.

**Comment by vuori** [comment]
Ok, it probably has something to do with how `sudo -i` sets the environment then. Closing this since working with the alternate setup.
