### ISSUE TITLE
Unable to sign commits using gpg4win

### ISSUE THREAD

**Issue by augb** [vuori/weasel-pageant#3]
I have the ability to sign commits and tags on the Windows side of things using gpg4win. When I attempt to do so via `weasel-pageant`, I get the following:
```
$ git commit -a -S -m 'signed commit'
error: cannot run C:\Program Files (x86)\GnuPG\bin\gpg.exe: No such file or directory
error: could not run gpg.
fatal: failed to write commit object
$
```
Is there a way to pass in the `gpg.exe` in a WSL-friendly format?

**Comment by vuori** [comment]
`weasel-pageant` does not support forwarding the gpg agent or any other gpg-related functionality. Looks like you're trying to use a Windows path inside WSL, you can try using `/mnt/c/Program Files…` instead.

**Comment by augb** [comment]
@vuori Thank you for your quick reply. I understand the lack of support for gpg agent forwarding, etc.

To clarify, my use case is signing commits with a smart-card. My specific issue is that I _need_ the path to be the following:
```
[gpg]
	program = "C:\\Program Files (x86)\\GnuPG\\bin\\gpg.exe"
```
... in my git config for the Windows-side. For example, VS Code commit signing uses this path. 

I _also_ simultaneously need the path to be presented to WSL as `/mnt/c/Program Files (x86)/GnuPG/bin/gpg.exe` if I want to sign commits on the WSL-side.
