### ISSUE TITLE
Interacts badly with the ssh client agent forwarding

### ISSUE THREAD

**Issue by kergoth** [vuori/weasel-pageant#4]
To clarify, running `ssh -A somehost` with openssh from WSL to another host results in ssh-add failing to connect to pageant via weasel-pageant via the ssh connection.

**Comment by vuori** [comment]
I use it all the time without issues. Please send the output from running `weasel-pageant -d ssh -A some.host ssh-add -l`.

**Comment by kergoth** [comment]
Nevermind, my mistake. Sorry about that. Turns out I had connected over ssh without -A first, then added it to the second command, but I use shared ssh connections via ControlMaster, so it was connecting to the existing connection that wasn't forwarding the agent. Killing the persistent connection and reconnecting fixed it. Thanks!

**Comment by kergoth** [comment]
I did encounter an interesting message I'd never seen before, maybe an ssh version mismatch or something? Just worth noting: `warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)`

**Comment by vuori** [comment]
Good to hear that you got it working. That's certainly an interesting error, but I suspect that it's due something that Pageant is doing. WP only reads the authentication agent packet length and then passes the rest of the data as an opaque blob to Pageant (and the same for the response).
