### ISSUE TITLE
weasel-pageant: win32 helper died immediately

### ISSUE THREAD

**Issue by willemdh** [vuori/weasel-pageant#6]
Hello,

I've been using ssh-pageant for a while, which works fine. So I wanted to try the same with wsl and weasel-pageant, but I must be doing something wrong. After copying weasel-pageant and helper.exe to my homefolder and executing

```
eval $(./weasel-pageant -r)
ssh-pageant pid 4505
```

But when I ssh into a server (with pageant running and cert loaded in Windows), I get:

```
ssh myuser@myserver
/home/myuser/helper.exe: Invalid argument
weasel-pageant: win32 helper died immediately
```

Any idea what I might be doing wrong here?

Grtz

**Comment by vuori** [comment]
As far as I can tell, the Win32 interaction in WSL happens through some sort of magical plumbing that involves the Windows console subsystem. When you connect through SSH there is no Windows console which appears to break Win32 interop. I never use WSL through SSH, so I have never investigated this scenario in detail though.

A potential workaround is to start weasel-pageant with the `-a <somepath>` flag on the Windows desktop in a console window that you never close, and then use `-a <somepath> -r` when you connect over SSH. weasel-pageant will then re-use the existing `SSH_AUTH_SOCK` and communication with the Win32 interop happening through the console window you left open.

My feeling is that there is no elegant solution for this problem with WSL. Eventually weasel-pageant should be re-implemented as a standalone Win32 app that uses the Windows-side Unix domain sockets introduced in 1803.

**Comment by computergeek125** [comment]
Possibly related to #5.  @willemdh what version/build of windows are you using?

**Comment by spielkind** [comment]
Some issue for me, using the latest WSL/Windows build: 10.0.17134.137

**Comment by vuori** [comment]
I just tested this on build 17758 and everything works for me. Are problems still present for someone?

**Comment by jubalfh** [comment]
The issue resurfaced in recent insider builds, I'm afraid; I'm currently running the _Windows 10 Pro Insider Preview_, version 1809 (build 18282.1000), and the helper dies immediately with prompt `weasel-pageant: win32 helper died immediately`.

**Comment by computergeek125** [comment]
That's interesting.  So far it's stable on mine (same build)

**Comment by vuori** [comment]
Please open a new issue if the problem persists, I can't test with Insider Previews right now. Also try running simple commands like `ipconfig.exe > test.txt` and check that the output of `ipconfig` appears in the redirected file. This should indicate whether redirection are working at all.

However, it's likely that any problems on this front must be fixed by Microsoft.

**Comment by tstackhouse** [comment]
I'm running into the same issue, though it seems to be intermittent :/  I haven't been able to nail down exactly when it works and when it doesn't, though seemingly respawning my WSL instance by quitting out all my terminal instances (tmux/zsh) and my terminal emulator (hyper) seems to fix it, at least temporarily.

Win 10 Home Insider Build, version 1809, build 17763.195

**Comment by webster42** [comment]
Also seeing this issue.
I, too am using tmux/zsh/hyper and the same Windows 10 Build like @tstackhouse .

**Comment by tstackhouse** [comment]
I will investigate next time the issue occurs.  As I said, completely reinitializing my session appears to temporarily alleviate the situation for an indeterminate amount of time. Will also investigate wsl-ssh-pageant should the need arise.  Thanks for making this :)
