### ISSUE TITLE
installation?

### ISSUE THREAD

**Issue by mailinglists35** [vuori/weasel-pageant#8]
from readme:
"Installation
From binaries

Download the zip file from the releases page and unpack it in a convenient location on the Windows part of your drive. Because WSL can only execute Win32 binaries from drvfs locations, weasel-pageant will not work if unpacked inside the WSL filesystem (onto an lxfs mount). (Advanced users may place only helper.exe on drvfs, but in general it is easier to keep the pieces together.)"

i don't understand this.

traditionally on linux i do either one of these:
1 - add some repo, apt update, apt install blah
2 - git clone / download tar.gz source, unpack, ./configure, make, make install

why is this app so non-standard? why do I must download an .exe and access it from wsl? why not build it from inside wsl, or download directly prebuild .deb?

**Comment by vuori** [comment]
If you'd like to streamline the build or installation processes, feel free to submit a pull request with improvements.

As for the exe question, a WSL process can't access Win32 desktop objects directly but must launch a Win32 helper to do it. The roles of the executables should be pretty easy to deduce from the source.

**Comment by mailinglists35** [comment]
>It works by executing from the WSL side a Win32 helper program which interfaces with Pageant and communicating with it through pipes.

oops sorry i missed that part!

so it's a two binaries app that it has one wsl component and a win32 component.

does the requirement for the win32 component to be on a drvfs path accessible inside wsl is to automatically launch the win32 component? can i launch them separately? or do the wsl need to give special instructions to the win32 component by launching it?
